### ISSUE TITLE
Improve upload error handling

### ISSUE THREAD

**Issue by mzur** [biigle/user-storage#11]
Improve the upload error handling as follows: If there is an error for an uploaded file, show a popup displaying the error (and the filename). The popup should offer an option to cancel the upload or to skip this file and continue with the remaining files.

**Comment by mzur** [comment]
In addition: If there is an error with an uploaded file, retry the upload after 10 s (?). If this also fails, show the error. This can be helpful if the BIIGLE instance is updated during an upload und unavailable for a few seconds.

**Comment by mzur** [comment]
@lehecht Can you please have a look at this sometime? I see quite a few errors where file uploads abort because the object storage temporarily doesn't work. A simple retry and better error handling would be nice. The retry should also be done for chunked large files.

**Comment by lehecht** [comment]
> In addition: If there is an error with an uploaded file, retry the upload after 5 s (?).

There is already a mechanism to [retry uploading](https://github.com/biigle/user-storage/blob/80f23dd24e985f6733008f3fdcb0a4ad4b50ca47/src/Http/Controllers/Api/StorageRequestFileController.php#L96-L109) the image. Should I replace this with your idea or maybe just increase the number of retries?

**Comment by mzur** [comment]
This issue is about the client-side upload. It works like this:
```
Client -> Server -> Storage
```
The retry you linked is from Server to Storage. This issue is about a retry and better error handling from Client to Server. Maybe it has a retry mechanism, too (I don't remember and didn't look), but the "skip or cancel" popup should also be added.

**Comment by mzur** [comment]
On second thought, a popup might not be the ideal solution. I imagine sometimes people just let large volumes of data upload unsupervised (e.g. over night). Then they come back in the morning and see an error after the first file and the popup, so the rest of the files were not uploaded. A better way would be to automatically skip files with errors and then at the end (when all files without errors were uploaded) show a popup asking to retry or skip the failed files.

**Comment by lehecht** [comment]
> The retry you linked is from Server to Storage. This issue is about a retry and better error handling from Client to Server. Maybe it has a retry mechanism, too (I don't remember and didn't look), but the "skip or cancel" popup should also be added.

What I meant was, if I should replace the number of retries by the 'retry after 5 s'-idea on the client side.

**Comment by mzur** [comment]
Is there a retry mechanism on the client side then? The Server to Storage retry mechanism should not be changed. The client side retry mechanism can have the 5 s delay.

**Comment by lehecht** [comment]
> Is there a retry mechanism on the client side then?

Yes, [there](https://github.com/biigle/user-storage/blob/80f23dd24e985f6733008f3fdcb0a4ad4b50ca47/src/resources/assets/js/createContainer.vue#L430-L432) it uses also 2 retries.

**Comment by lehecht** [comment]
> The client side retry mechanism can have the 5 s delay

So should I replace the former mechanism or add this delay?

**Comment by lehecht** [comment]
> [...] show a popup asking to retry or skip the failed files.

What do you think about this alternative to a popup? I saw something similar for already initialized files that were not uploaded.
But if you prefer a popup, I'll use one.
![Bildschirmfoto vom 2024-04-10 10-13-27](https://github.com/biigle/user-storage/assets/72259845/dde2a1b9-7b42-494c-b7e7-d5ac7d965a28)

**Comment by mzur** [comment]
I like your idea! Some additional thoughts:

- Maybe the failed files can also be highlighted with `text-warning`
- The "Add directory, ..., Submit" buttons should disappear as they no longer make sense in this context
- The "Re-upload, ..." buttons can have normal size
- The "Re-upload" button can have `btn-success` as this is the recommended option
- The whole message with buttons could be displayed inside a:
   ```html
   <div class="panel panel-warning">
      <div class="panel-body text-warning>
      </div>
   </div>
   ```
   This is the box that BIIGLE also uses elsewhere.
- Alternative button labels could be "retry failed files" and "skip failed files" to make the actions very clear.

**Comment by lehecht** [comment]
@mzur 
> Maybe the failed files can also be highlighted with `text-warning`

Should I extend the fileBrowser component and its used components or apply the changes directly in these core files?

**Comment by mzur** [comment]
It's probably easier to update the core files, right? You can add a new optional property `warningFiles` or some such as an array of files that should be highlighted. If the prop is not given, the file browser behaves as before.

**Comment by lehecht** [comment]
@mzur 

How should I handle failed files with very long file names? It could happen, that the "failed" info is not (completly) visible anymore because of the box size.
![Bildschirmfoto vom 2024-04-19 10-59-17](https://github.com/biigle/user-storage/assets/72259845/831d7837-e449-4f93-b6b9-9f2dfb8addf0)

**Comment by mzur** [comment]
Also the directory tree above the failed file should be colored (but without warning icon).
